# Generated by Django 4.1 on 2022-09-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boshliq', '0002_alter_tovar_mahsulot_hajmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='umumiy_miqdori',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
