# Generated by Django 4.1 on 2022-09-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boshliq', '0003_alter_tovar_umumiy_miqdori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='mahsulot_hajmi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
